sudo: required
language: python
services:
  - docker
addons:
  apt:
    sources:
      - sourceline: 'https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'
        key_url: 'https://download.docker.com/linux/ubuntu/gpg'
    packages:
      - docker-ce

install:
  - pip install molecule docker-py

script:
  - molecule test