---
- name: install base packages
  become: true
  yum:
    update_cache: true
    name: ["curl", "gcc-c++", "make"]
    state: present
- name: curl the LTS setup
  get_url:
    dest: "{{ ansible_env.HOME }}/nodesetup"
    url: "{{ centos_lts }}"
    mode: 0775
    timeout: 10
    validate_certs: true
  when: lts
- name: curl the latest
  get_url:
    dest: "{{ ansible_env.HOME }}/nodesetup"
    url: "{{ centos_latest }}"
    mode: 0775
    timeout: 10
    validate_certs: true
  when: not lts
- name: execute the node setup script
  become: true
  command: "bash -c {{ ansible_env.HOME }}/nodesetup"
  args:
    creates: /etc/yum.repos.d/nodesource-el7.repo
- name: install desired version of nodejs
  become: true
  yum:
    update_cache: true
    name: nodejs
    state: present
